<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>A simple-to-use encryption service.</Description>
    <PackageProjectUrl>https://github.com/panoramicdata/PanoramicData.Encryption</PackageProjectUrl>
    <PackageIcon>PanoramicData.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/panoramicdata/PanoramicData.Encryption</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>simple;encryption</PackageTags>
    <PackageReleaseNotes>Initial release</PackageReleaseNotes>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageId>PanoramicData.Encryption</PackageId>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <NeutralResourcesLanguage>en</NeutralResourcesLanguage>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IDisposableAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nerdbank.GitVersioning">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SecurityCodeScan.VS2019">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="PanoramicData.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>